### ISSUE TITLE
是不是该更新一下呢?

### ISSUE THREAD

**Issue by cleven1** [Liaoworking/MoyaNetworkTool#2]
大佬  是时候更新一下呢 你觉得呢?

**Comment by Liaoworking** [comment]
好的  我觉得可以哈哈    整理好思路了再发一个优化版本啊

**Comment by Liaoworking** [comment]
大兄弟，我更新好了    感觉实现细节可以优化一下  哈哈等我想明白了 再来一个优化版本。
共勉~
