### ISSUE TITLE
有HandyJSON的版本吗

### ISSUE THREAD

**Issue by Liyongcong** [Liaoworking/MoyaNetworkTool#9]

**Comment by Liaoworking** [comment]
我一年前的commit就是handyJSON版本的，包括我们项目中也是用的HandyJSON版本，只不过HandyJSON不太稳定，开源的角度就改成了其他版本。 你可以clone下来版本回退到之前的版本查看HandyJSON版本的用法。

**Comment by Liaoworking** [comment]
这个版本是HandyJSON的： https://github.com/Liaoworking/MoyaNetworkTool/tree/d5302295834da75d9501af6be4369249fa0f1eee

**Comment by Liyongcong** [comment]
好的多谢，刚入手Swift，谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Liaoworking/MoyaNetworkTool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月15日(星期四) 晚上6:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Liaoworking/MoyaNetworkTool] 有HandyJSON的版本吗 (#9)





 
Closed #9.

**Comment by Liyongcong** [comment]
我直接pod&nbsp;HandyJSON的最新版本就可以了吧
 

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Liaoworking/MoyaNetworkTool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月15日(星期四) 晚上6:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Liaoworking/MoyaNetworkTool] 有HandyJSON的版本吗 (#9)





 
Closed #9.
